platform :ios, '10.0'

use_frameworks!

source 'git@github.com:applicaster/CocoaPods.git'
source 'git@github.com:applicaster/CocoaPods-Private.git'
source 'https://cdn.cocoapods.org'

def shared_pods
    pod 'ZappPlugins'
    pod 'ZappLoginPluginsSDK'
end

target 'DIRTVisionInplayerWebviewLogin' do
  shared_pods
end

target 'DIRTVisionInplayerWebviewLoginTests' do
  shared_pods
end
