platform :ios, '10.0'

use_frameworks!

source 'git@github.com:applicaster/CocoaPods.git'
source 'git@github.com:applicaster/CocoaPods-Private.git'
source 'git@github.com:CocoaPods/Specs.git'

def shared_pods
    pod 'ZappPlugins'
    pod 'ZappLoginPluginsSDK'
end

target 'InPlayerWebviewLogin' do
  shared_pods
end

target 'InPlayerWebviewLoginTests' do
  shared_pods
end